name: Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run rust tests
        run: cargo test --verbose

      - uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync
      - name: Run python tests
        run: uv run pytest
